DoctorApp/Models/ErrorViewModel.cs
namespace DoctorApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DoctorApp/Models/Patient.cs
using System.ComponentModel.DataAnnotations;

namespace DoctorApp.Models
{
    public class Patient
    {
        [Key]
        public int Id { get; set; }
        public int Amount { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}

DoctorApp/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace DoctorApp.Controllers
{
    public class DashboardController : Controller
    {
        public IActionResult Dashboard()
        {
            return View();
        }
    }
}

DoctorApp/Controllers/HomeController.cs
using DoctorApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace DoctorApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DoctorApp/Controllers/PatientsController.cs
using DoctorApp.DataContext;
using DoctorApp.Interface;
using DoctorApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace DoctorApp.Controllers
{
    public class PatientsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly IPatientRepository _patientRepository;
        public PatientsController(ApplicationDbContext context, IPatientRepository _patientRepository)
        {
            _context = context;
            this._patientRepository = _patientRepository;
        }

        // GET: Patients
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetCompanyData()
        {
            var data = await _patientRepository.GetAllPatient();
            return Json(data);
        }


        // GET: Patients/Create
        public async Task<IActionResult> Create()
        {
            var amount = await _patientRepository.TotalAmount();
            ViewData["amount"] = amount;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Patient patient)
        {
            await _patientRepository.AddPatient(patient);
            return RedirectToAction("Create");
        }

        // GET: Patients/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient.FindAsync(id);
            if (patient == null)
            {
                return NotFound();
            }
            return View(patient);
        }

        // POST: Patients/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PatientNo,Amount,CreatedDate,UpdateDate")] Patient patient)
        {
            if (id != patient.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(patient);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PatientExists(patient.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(patient);
        }

        // GET: Patients/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var patient = await _context.Patient
                .FirstOrDefaultAsync(m => m.Id == id);
            if (patient == null)
            {
                return NotFound();
            }

            return View(patient);
        }

        // POST: Patients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var patient = await _context.Patient.FindAsync(id);
            if (patient != null)
            {
                _context.Patient.Remove(patient);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PatientExists(int id)
        {
            return _context.Patient.Any(e => e.Id == id);
        }
    }
}

DoctorApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="col-md-6">
    <div class="card">
        <div class="card-header">Line Chart</div>
        <div class="card-body">
            <p class="card-title"></p>
            <div class="canvas-wrapper">
                <canvas class="chart" id="linechart"></canvas>
            </div>
        </div>
    </div>
</div>

DoctorApp/Views/Patients/Create.cshtml
@model DoctorApp.Models.Patient

@{
    ViewData["Title"] = "Create";
}

<div class="row">
    <div class="patient-form">
        <form asp-action="Create" id="createPatientForm">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control mt-2" style="width:20rem;" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" id="tableReload" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
@* <partial name="_PatientTable" /> *@
<div class="row">
    <div class="col-md-12">
        <button id="togglePartialView" class="btn btn-secondary">View history</button>
    </div>
</div>

<div id="partialViewContainer" class="mt-3" style="display: none;">
    <p>Total amount : @ViewData["amount"]</p>
    <partial name="_PatientTable" />
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script asp-src-include="~/js/Patient.js"></script>
        <script>
            $(document).ready(function () {
                $('#togglePartialView').click(function () {
                    $('#partialViewContainer').toggle();
                });
            });
        </script>
    }
}

DoctorApp/Views/Patients/Delete.cshtml
@model DoctorApp.Models.Patient

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Patient</h4>
    <hr />
    <dl class="row">
         
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DoctorApp/Views/Patients/Edit.cshtml
@model DoctorApp.Models.Patient

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Patient</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UpdateDate" class="control-label"></label>
                <input asp-for="UpdateDate" class="form-control" />
                <span asp-validation-for="UpdateDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoctorApp/Views/Patients/Index.cshtml
@model IEnumerable<DoctorApp.Models.Patient>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
@* <table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UpdateDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>

            <td>
                @Html.DisplayFor(modelItem => item.Amount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UpdateDate)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table> *@
<partial name="_PatientTable" />
@* <table id="example" class="display" style="width:100%">
    <thead>
        <tr>
            <th>Amount</th>
        </tr>
    </thead>
    <tbody>
        <!-- Table data will be populated dynamically -->
    </tbody>
</table> *@
@section Scripts {
    @{
        <script asp-src-include="~/js/Patient.js"></script>
    }
}

DoctorApp/Views/Patients/_PatientTable.cshtml
<div class="patient-table">
    <table id="example" class="display" style="width:100%; padding-top: 1rem;">
        <thead>
            <tr>
                <th></th>
                <th>Amount</th>
                <th>Created Date</th>
            </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>

DoctorApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DoctorApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DoctorApp.styles.css" asp-append-version="true" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DoctorApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="Create">Patient Amount</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Dashboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DoctorApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/chartsjs/chart.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <!-- Include DataTables JS -->
    <script type="text/javascript" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>